name: MinecubedTweaks
version: '${project.version}'
main: com.minecubedmc.Tweaks
api-version: 1.18
softdepend:  [ItemsAdder, RealisticSeasons, HeadDatabase, Essentials, AureliumSkills, MythicMobs, AuthMe, LiteBans ]
load: POSTWORLD
authors: [ Kenified ]
description: Random assortment of tweaks for Minecubed server
