name: MinecubedTweaks
version: '${project.version}'
main: com.minecubedmc.Tweaks
api-version: 1.18
depend: [ItemsAdder]
authors: [ Kenified ]
description: Random assortment of tweaks for Minecubed server
